08_pjt/accounts/urls.py
from django.urls import path 
from . import views 
 
app_name = 'accounts' 
 
urlpatterns = [
    path('signup/', views.signup, name='signup'), 
    path('login/', views.login, name='login'), 
    path('logout/', views.logout, name='logout'), 
    path('<username>/', views.profile, name='profile'), 
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

08_pjt/community/urls.py
from django.urls import path 
from . import views 
 
app_name = 'community' 
 
urlpatterns = [ 
    path('', views.index, name='index'), 
    path('create/', views.create, name='create'), 
    path('<int:review_pk>/', views.detail, name='detail'), 
    path('<int:review_pk>/comments/create/', views.create_comment, name='create_comment'), 
    path('<int:review_pk>/like/', views.like, name='like'), 
]

08_pjt/movies/urls.py
from django.urls import path 
from . import views 
 
app_name = 'movies' 
 
urlpatterns = [ 
    path('', views.index, name='index'), 
    path('<int:movie_pk>/', views.detail, name='detail'), 
    path('recommended/', views.recommended, name='recommended'), 
]

08_pjt/pjt08/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

08_pjt/templates/base.html
<!DOCTYPE html> 
<html lang="en"> 
  <head> 
    <meta charset="UTF-8" /> 
    <meta http-equiv="X-UA-Compatible" content="IE=edge" /> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0" /> 
    <title>Document</title> 
  </head> 
  <body> 
    <nav> 
        {% if user.is_authenticated %} 
          <h3>Hello, {{ user.username }}</h3> 
          <a href="{% url 'accounts:profile' user %}">내 프로필<a>
          <form action="{% url 'accounts:logout' %}" method="POST"> 
            {% csrf_token %} 
            <input type="submit" value="Logout" /> 
          </form> 
          <a href="{% url 'movies:index'%}">Movie</a> 
        <a href="{% url 'community:index'%}">Community</a> 
        <a href="{% url 'community:create'%}">New Review</a>
        {% else %} 
          <a href="{% url 'accounts:login' %}">Login</a> 
          <a href="{% url 'accounts:signup' %}">Signup</a> 
        {% endif %} 
      </nav> 
    <hr> 
    <div> 
      {% block content %} 
      {% endblock content %} 
    </div> 
 
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script> 
    {% block script %} 
    {% endblock script %} 
  </body> 
</html>